=== unicode-org/inflection/inflection/resources/org/unicode/inflection/features/grammar.dtd
<!--
 Copyright 2015-2024 Apple Inc. All rights reserved.
-->
<!-- @author George Rhoten 2015-01-21 -->
<!ELEMENT languages (common, language+)>
<!ELEMENT common (grammar?, features?)>
<!ELEMENT language (grammar?, features?)>
<!ELEMENT grammar (category+)>
<!ELEMENT category (restrictions?, grammeme+)>
<!ELEMENT restrictions (restriction+)>
<!ELEMENT restriction EMPTY>
<!ELEMENT features (feature+)>
<!ELEMENT feature (value*)>
<!ELEMENT grammeme (restrictions?)>
<!ELEMENT value EMPTY>

<!ATTLIST language id CDATA #REQUIRED>
<!ATTLIST category name CDATA #REQUIRED>
<!ATTLIST category aliasable (true|false) "true">
<!ATTLIST restriction name CDATA #REQUIRED>
<!ATTLIST restriction value CDATA #REQUIRED>
<!ATTLIST grammeme name CDATA #REQUIRED>
<!ATTLIST feature name CDATA #REQUIRED>
<!ATTLIST feature default CDATA #IMPLIED>
<!ATTLIST value result CDATA #REQUIRED>
<!ATTLIST value case CDATA #IMPLIED>
<!ATTLIST value number CDATA #IMPLIED>
<!ATTLIST value gender CDATA #IMPLIED>
<!ATTLIST value sound CDATA #IMPLIED>

=== unicode-org/inflection/inflection/resources/org/unicode/inflection/features/grammar.xml
<?xml version='1.0' encoding='utf-8'?>
<!--
 Copyright 2025 Unicode Incorporated and others. All rights reserved.
 Copyright 2016-2024 Apple Inc. All rights reserved.
-->
<!DOCTYPE languages SYSTEM "grammar.dtd">
<languages>
    <!-- This file contains all the semantic features for SemanticConcept objects. -->
    <!--
     The grammar categories can be used as annotation of tokens in addition to the properties provided by the DictionaryMetaData class.
     So similar concepts should not diverge in name. The features are not used with DictionaryMetaData.
      -->
    <!-- @author George Rhoten 2015-01-23 -->
    <common>
        <!-- This is the common stuff regardless of what the other languages specify. -->
        <grammar>
            <category name="pos">
                <grammeme name="abbreviation"/>
                <grammeme name="adjective"/>
                <grammeme name="adverb"/>
                <!-- grammeme name="article" -->
                <grammeme name="conjunction"/>
                <!-- grammeme name="determiner" -->
                <grammeme name="interjection"/>
                <!-- grammeme name="letter"/ -->
                <grammeme name="noun"/>
                <grammeme name="numeral"/>
                <!-- grammeme name="participle" -->
                <grammeme name="particle"/>
                <!-- grammeme name="postposition"/ -->
                <!-- grammeme name="preposition" -->
                <grammeme name="proper-noun"/>
                <grammeme name="pronoun"/>
                <grammeme name="verb"/>
            </category>
            <category name="sound">
                <grammeme name="vowel-start"/>
                <grammeme name="consonant-start"/>
                <grammeme name="vowel-end"/>
                <grammeme name="consonant-end"/>
            </category>
        </grammar>
        <features>
            <feature name="speak"/>
        </features>
    </common>
    <language id="ar">
        <grammar>
            <category name="animacy">
                <grammeme name="human"/>
                <grammeme name="nonhuman"/>
            </category>
            <category name="case">
                <grammeme name="accusative"/>
                <grammeme name="genitive"/>
                <grammeme name="nominative"/>
            </category>
            <category name="number">
                <grammeme name="singular"/>
                <grammeme name="dual"/>
                <grammeme name="plural"/> <!-- other -->
            </category>
            <category name="numberPronoun" aliasable="false">
                <grammeme name="singular"/>
                <grammeme name="dual"/>
                <grammeme name="plural"/> <!-- other -->
            </category>
            <category name="definiteness"><!-- state -->
                <grammeme name="definite"/>
                <grammeme name="indefinite"/>
                <grammeme name="construct"/>
            </category>
            <category name="gender">
                <grammeme name="masculine"/>
                <grammeme name="feminine"/>
            </category>
            <category name="genderPronoun" aliasable="false">
                <grammeme name="masculine"/>
                <grammeme name="feminine"/>
            </category>
            <category name="person">
                <grammeme name="first"/>
                <grammeme name="second"/>
                <grammeme name="third"/>
            </category>
            <category name="pronounType">
                <restrictions>
                    <restriction name="pos" value="pronoun"/>
                </restrictions>
                <grammeme name="personal"/>
                <grammeme name="reflexive"/>
            </category>
            <category name="mood">
                <restrictions>
                    <restriction name="pos" value="verb"/>
                </restrictions>
                <grammeme name="imperative"/>
                <grammeme name="indicative"/>
                <grammeme name="jussive"/>
                <grammeme name="subjunctive"/>
                <!-- long and short energetic? -->
            </category>
            <category name="tense">
                <grammeme name="past"/>
                <grammeme name="present"/>
                <grammeme name="future"/>
            </category>
        </grammar>
        <features>
            <feature name="reflexivePron"/>
            <feature name="withPossessivePron"/>
            <feature name="withToPrep"/> <!--ل -->
            <feature name="withWithPrep"/> <!-- ب -->
            <feature name="withAndPrep"/> <!-- و -->
            <feature name="withAsPrep"/> <!-- ك-->
        </features>
    </language>
    <language id="bg">
        <grammar>
            <category name="case">
                <restrictions>
                    <restriction name="pos" value="noun"/>
                    <restriction name="pos" value="proper-noun"/>
                </restrictions>
                <grammeme name="accusative">
                    <restrictions>
                        <restriction name="pos" value="pronoun"/>
                    </restrictions>
                </grammeme>
                <grammeme name="dative">
                    <restrictions>
                        <restriction name="pos" value="pronoun"/>
                    </restrictions>
                </grammeme>
                <grammeme name="genitive">
                    <restrictions>
                        <restriction name="pos" value="pronoun"/>
                    </restrictions>
                </grammeme>
                <grammeme name="nominative"/>
                <grammeme name="vocative"/>
            </category>
            <category name="number">
                <grammeme name="singular"/>
                <grammeme name="plural"/>
            </category>
            <category name="definiteness">
                <grammeme name="definite"/>
                <grammeme name="indefinite"/>
            </category>
            <category name="emphasis">
                <restrictions>
                    <restriction name="pos" value="pronoun"/>
                </restrictions>
                <grammeme name="stressed"/>
                <grammeme name="unstressed"/>
            </category>
            <category name="gender">
                <grammeme name="masculine"/>
                <grammeme name="feminine"/>
                <grammeme name="neuter"/>
            </category>
            <category name="person">
                <grammeme name="first"/>
                <grammeme name="second"/>
                <grammeme name="third"/>
            </category>
            <category name="pronounType">
                <restrictions>
                    <restriction name="pos" value="pronoun"/>
                </restrictions>
                <grammeme name="personal"/>
                <grammeme name="reflexive"/>
            </category>
        </grammar>
    </language>
    <language id="ca">
        <grammar>
            <category name="case">
                <restrictions>
                    <restriction name="pos" value="pronoun"/>
                </restrictions>
                <grammeme name="nominative"/>
                <grammeme name="genitive"/> <!-- AKA possessive -->
                <grammeme name="accusative"/>
                <grammeme name="dative"/>
            </category>
            <category name="gender">
                <grammeme name="masculine"/>
                <grammeme name="feminine"/>
                <grammeme name="neuter"/>
            </category>
            <category name="number">
                <grammeme name="singular"/>
                <grammeme name="plural"/>
            </category>
            <category name="definiteness">
                <grammeme name="definite"/>
                <grammeme name="indefinite"/>
            </category>
            <category name="pos">
                <restrictions>
                    <restriction name="pos" value="pronoun"/>
                </restrictions>
                <grammeme name="adposition"/>
            </category>
            <category name="person">
                <restrictions>
                    <restriction name="pos" value="pronoun"/>
                </restrictions>
                <grammeme name="first"/>
                <grammeme name="second"/>
                <grammeme name="third"/>
            </category>
            <category name="position">
                <grammeme name="proclitic"/>
                <grammeme name="enclitic"/>
            </category>
            <category name="pronounType">
                <restrictions>
                    <restriction name="pos" value="pronoun"/>
                </restrictions>
                <grammeme name="personal"/>
                <grammeme name="reflexive"/>
            </category>
            <category name="register">
                <restrictions>
                    <restriction name="pos" value="pronoun"/>
                </restrictions>
                <grammeme name="casual"/> <!-- AKA informal, but not to be confused with intimate -->
                <grammeme name="formal"/>
            </category>
        </grammar>
    </language>
    <language id="bn">
        <grammar>
            <category name="animacy">
                <grammeme name="animate"/>
                <grammeme name="inanimate"/>
            </category>
            <category name="case">
                <grammeme name="accusative"/>
                <grammeme name="genitive"/>
                <grammeme name="locative"/>
                <grammeme name="nominative"/>
            </category>
            <category name="number">
                <grammeme name="singular"/>
                <grammeme name="plural"/>
            </category>
            <category name="person">
                <grammeme name="first"/>
                <grammeme name="second"/>
